var res = {
	//png UI
	pngFooter_png : "res/pngUI/pngFooter.png",
	pngHeader_png : "res/pngUI/pngHeader.png",
	pngHome1_png : "res/pngUI/pngHome1.png",
	pngHome2_png : "res/pngUI/pngHome2.png",
	pngLocation1_png : "res/pngUI/pngLocation1.png",
	pngLocation2_png : "res/pngUI/pngLocation2.png",
	pngLogo_png : "res/pngUI/pngLogo.png",
	pngMyPosts1_png : "res/pngUI/pngMyPosts1.png",
	pngMyPosts2_png : "res/pngUI/pngMyPosts2.png",
	pngPostAnAd1_png : "res/pngUI/pngPostAnAd1.png",
	pngPostAnAd2_png : "res/pngUI/pngPostAnAd2.png",
	pngSearch_png : "res/pngUI/pngSearch.png",
	pngSettings1_png : "res/pngUI/pngSettings1.png",
	pngSettings2_png : "res/pngUI/pngSettings2.png",
	pngTableCellA1_png : "res/pngUI/pngTableCellA1.png",
	pngTableCellB1_png : "res/pngUI/pngTableCellB1.png",
	pngTableCellC1_png : "res/pngUI/pngTableCellC1.png",
	pngTableCellA2_png : "res/pngUI/pngTableCellA2.png",
	pngTableCellB2_png : "res/pngUI/pngTableCellB2.png",
	pngTableCellC2_png : "res/pngUI/pngTableCellC2.png",
	pngCellTab_png : "res/pngUI/pngCellTab.png",
	pngBlank_png : "res/pngUI/pngBlank.png",
	pngLoading1_png : "res/pngUI/pngLoading1.png",
	pngLoading2_png : "res/pngUI/pngLoading2.png",
	pngLoading3_png : "res/pngUI/pngLoading3.png",
	pngLoading4_png : "res/pngUI/pngLoading4.png",
	pngLoading5_png : "res/pngUI/pngLoading5.png",
	pngEmail_png : "res/pngUI/pngEmail.png",
	pngPhone_png : "res/pngUI/pngPhone.png",
	pngConditionBox_png : "res/pngUI/pngConditionBox.png",
	pngAdvertise_png : "res/pngUI/pngAdvertise.png",
	pngOneBox_png : "res/pngUI/pngOneBox.png",
	pngTwoBox_png : "res/pngUI/pngTwoBox.png",
	pngThreeBox_png : "res/pngUI/pngThreeBox.png",
	pngBigTableCellA1_png : "res/pngUI/pngBigTableCellA1.png",
	pngBigTableCellB1_png : "res/pngUI/pngBigTableCellB1.png",
	pngBigTableCellC1_png : "res/pngUI/pngBigTableCellC1.png",
	pngBigTableCellA2_png : "res/pngUI/pngBigTableCellA2.png",
	pngBigTableCellB2_png : "res/pngUI/pngBigTableCellB2.png",
	pngBigTableCellC2_png : "res/pngUI/pngBigTableCellC2.png",
	pngStar1_png : "res/pngUI/pngStar1.png",
	pngStar2_png : "res/pngUI/pngStar2.png",
	pngViewBox_png : "res/pngUI/pngViewBox.png",
	pngViewDivider_png : "res/pngUI/pngViewDivider.png",
	pngNoPhoto_png : "res/pngUI/pngNoPhoto.png",
	pngSmallIcon1_png : "res/pngUI/pngSmallIcon1.png",
	pngSmallIcon2_png : "res/pngUI/pngSmallIcon2.png",
	pngSmallIcon3_png : "res/pngUI/pngSmallIcon3.png",
	pngSmallIcon4_png : "res/pngUI/pngSmallIcon4.png",
	pngSmallIcon5_png : "res/pngUI/pngSmallIcon5.png",
	pngSmallIcon6_png : "res/pngUI/pngSmallIcon6.png",
	
	//bmpFont
	fntmasSulit24_fnt : "res/bmpFont/masSULIT24.fnt",
	fntmasSulit24_png : "res/bmpFont/masSULIT24_0.png",
	fntmasSulit32_fnt : "res/bmpFont/masSULIT32.fnt",
	fntmasSulit32_png : "res/bmpFont/masSULIT32_0.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}